default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: root  

development:
  <<: *default
  database: simple_form_search_development

test:
  <<: *default
  database: simple_form_search_test

staging:
  <<: *default

production:
  <<: *default

